### ISSUE TITLE
UI problem on android

### ISSUE THREAD

**Issue by huy-lv** [syednomishah/Coffee-App-React-Native#1]
You project is really great, but I think you forget to test on android, please check this :D

![Screenshot_20230426_105037_Expo Go](https://user-images.githubusercontent.com/7688070/234465682-3a8ce5e9-6da6-48f9-b090-5b4325e6769a.jpg)

**Comment by syednomishah** [comment]
It's not responsive on all devices, i will make it responsive when i get time ;)

**Comment by syednomishah** [comment]
Added responsiveness for all devices ;)
